name: Atlas-MD Bot

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Start Bot
        env:
          MONGO_URL: ${{ secrets.MONGO_URL }}
          MONGODB_URI: ${{ secrets.MONGO_URL }}
          MONGODB_URL: ${{ secrets.MONGO_URL }}
          SESSION_ID: ${{ secrets.SESSION_ID }}
          OWNER_NUMBER: ${{ secrets.OWNER_NUMBER }}
        run: npm start
